# Generated by Django 2.1.7 on 2019-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='remote_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
