"""
Django settings for myblog project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, `
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
# choose settings between Developement and Deploy
import os
import platform

node = platform.node()
print(node)
dev_machines = ('cheng-cx', 'cheng-cx.local','localhost','study.centos.changxin')
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if node in dev_machines:
    print('Debug')
    # folder BASE_DIR or project myblog dir which is the same as app folder.
    myblog = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    # project dir, contains static and media folder under deploy environment
    PROJECT_DIR = os.path.dirname(myblog)
    print('MyBlog:',myblog,'\nPROJECT_DIR:', PROJECT_DIR)
    DEBUG =  True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'blogcx',
            'USER': 'root',
            'PASSWORD': '123456',
            'PORT': '3306',
        }
    }
    STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
    STATIC_URL = '/static/'
    MEDIA_ROOT = os.path.join(PROJECT_DIR, 'media')
    MEDIA_URL = '/media/'
    TEMPLATE_DIRS = [os.path.join(myblog, 'templates')]
    ALLOWED_HOSTS = ['*']
else:
    print('deploy')
    DEBUG = True
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'blogcx',
            'USER': 'root',
            'PASSWORD': 'Nio@1968',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

    STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')
    STATIC_URL = '/static/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = '/media/'


    ALLOWED_HOSTS = [
        '*',
    ]
